## Copyright (c) 2021 Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
import os
import traceback
import logging
from flask import Flask, request
import oracledb
import sample_env

# Port to listen on
port=int(os.environ.get('PORT', '8080'))

# create_schema(): drop and create the demo table, and add a row
def create_schema():
    with oracledb.connect(user=sample_env.get_main_user(),
                            password=sample_env.get_main_password(),
                            dsn=sample_env.get_connect_string()) as connection:
        with connection.cursor() as cursor:
            cursor.execute("""
                begin
                  begin
                    execute immediate 'drop table demo';
                    exception when others then
                      if sqlcode <> -942 then
                        raise;
                      end if;
                  end;

                  execute immediate 'create table demo (
                       id       number generated by default as identity,
                       username varchar2(40))';

                  execute immediate
                         'insert into demo (username) values (''chris'')';

                  commit;
                end;""")

#------------------------------------------------------------------------------

app = Flask(__name__)

# Display a welcome message on the 'home' page
@app.route('/')
def index():
    return "Welcome to the demo app"

# Show name of thing
@app.route("/user/<int:id>")
def get_user_by_id(id):
    app.logger.warning("Probe: %s" % request.args.get('probe','NO-PROBE'))
    app.logger.warning("USER: %s" % sample_env.get_main_user())
    app.logger.warning("PASSWORD: %s" % sample_env.get_main_password())
    app.logger.warning("DSN: %s" % sample_env.get_connect_string())
    sql = "select username from demo where id = :idbv"
    conn = oracledb.connect(user=sample_env.get_main_user(),
                            password=sample_env.get_main_password(),
                            dsn=sample_env.get_connect_string())
    cursor = conn.cursor()
    cursor.execute(sql, [id])
    r = cursor.fetchone()
    conn.close()
    return r[0] if r is not None else "UNKNOWN"

#------------------------------------------------------------------------------

if __name__ == '__main__':

    # Create a demo table
    # create_schema()

    # Start a webserver
    app.run(port=port)
